# Generated by Django 5.2.5 on 2025-11-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_bio_alter_profile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_pic',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
    ]
